spring:
  profiles:
    active: dev
springdoc:
  description: @description@
  version: @version@
  title: @name@
mybatis:
  type-aliases-package: com.elysantos.desafiosouth.model.domain
  type-handlers-package: com.elysantos.desafiosouth.repository.typehandler
  mapper-locations: classpath*:**/mappers/*.xml
external-validator: https://user-info.herokyapp.com/users/
topic:
  name: assembleias-resultados
  bootstrap-server: localhost:9092
---
# Configurações de Desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    password: south
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
server:
  port: 9898
external-validator: http://localhost:8099/