spring:
  profiles:
    active: dev
springdoc:
  description: @description@
  version: @version@
  title: @name@
mybatis:
  type-aliases-package: com.elysantos.desafiosouth.model.domain
  type-handlers-package: com.elysantos.desafiosouth.mapper.typehandler
  mapper-locations: classpath*:**/mappers/*.xml
external-validator: https://user-info.herokyapp.com/users/
---
# Configurações de Desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
      path: /console
server:
  port: 9990
external-validator: http://localhost:808/