spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
springdoc:
  description: @description@
  version: @version@
  title: @name@
---
# Configurações de Desenvolvimento
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
    enabled: true
    path: /console
server:
  port: 9990